# Generated by Django 3.1.5 on 2021-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Like',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
