# Generated by Django 3.1.5 on 2021-01-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210122_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.TextField(verbose_name='Main Text'),
        ),
    ]
